# Generated by Django 3.1 on 2020-09-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformsubmission',
            name='income',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
