# Generated by Django 3.1 on 2020-09-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customformsubmission_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformsubmission',
            name='home',
            field=models.IntegerField(default=0),
        ),
    ]
