# Generated by Django 3.1 on 2020-09-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customformsubmission_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformsubmission',
            name='home',
            field=models.CharField(default='', max_length=256),
        ),
    ]
